export const BookmarkIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    preserveAspectRatio="xMidYMid"
    width="47.974"
    height="47.974"
    viewBox="0 0 512 512"
  >
    <image
      xlinkHref="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB0AAAAwCAMAAADaf4HVAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAA8FBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmRfStAAAAT3RSTlMAzf7U2eHnKg0V9ugeCPcfARsFf5QHussSMu3aScn4Q269qoKuemjACynmQC/q8jliyA4EtnUToYdztD7E/Tg329MWCsLklYFUQvGzPCytlUXzcgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAACxIAAAsSAdLdfvwAAADKSURBVDjL7dTXTkJBFIXhTcejHBEpShEpKiJVRYqigAhK+9//bShRQ5nhmouzLudLJpM1yRIbdnRxiBN9XOLGI15V5AhDjjkRdXyYCz211FJLD0X9Z4E9ek5Qq6HwYg0iF2q9jBKLJ7hKqvQaUj6RNGR21J+Fm9XhLdzlNvU+j/Hwe2OhSKm8rhWoPv4/9ukZan/6InVobBTRhJbISl/faMe3enovEfuImtLBoNvbqfGzj8nXcicHypqHy53M8635hR9GMp6ILtPZHEixSrCO5p5VAAAAAElFTkSuQmCC"
      x="103"
      width="307"
      height="512"
    />
  </svg>
);

export default BookmarkIcon;
