export const LikeIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    preserveAspectRatio="xMidYMid"
    width="19.968"
    height="19.968"
    viewBox="0 0 512 512"
  >
    <image
      xlinkHref="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAASCAMAAABsDg4iAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAA21BMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9/cYNAAAASHRSTlMAkuHs69t8cNfimQQa8XQ5PYHuxLn1i0I62vkm/AamCZPqrPJoU/okE+Ulao/+6bMKGacrHowwH6UvIKKKMiGehzUjhjZ1OPv8QQi6AAAAAWJLR0QAiAUdSAAAAAlwSFlzAAALEgAACxIB0t1+/AAAAKlJREFUGNNtzucSwVAQBeCDSwjRgxAtOtE70aLt+z8RiSHJHfvnnPlmdmcBwOcPsGAIEMKMRcToWxCTIvFEMpXOZOVcviAoxdIb1SzsUVjZzgpVUVPBTV1Do8ljqw2pw2O3B6n/Dwd/1vUhjyMNaI+9JtIEmNLMbTrNrVhQxbElrT5lTRvHtt+6o/2nGHRwlo50suJMF/d509Ir3byPlMi404N/2ZSfv3svyJcRoDZknfgAAAAASUVORK5CYII="
      y="28"
      width="512"
      height="457"
    />
  </svg>
);

export default LikeIcon;
