export const ReplyIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    preserveAspectRatio="xMidYMid"
    width="19.968"
    height="19.968"
    viewBox="0 0 512 512"
  >
    <image
      xlinkHref="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAARCAMAAAAMs7fIAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAA4VBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzthe/AAAASnRSTlMAXbfy9LphAknm2/HsT2eDJCOAcD71LCfvSB73A1aJf8ARC8z+8OnRye7nxw4agohlAe0fKfkGNCiPqCGGeLzCyMrQ81jZ68NqCH2Nlx8AAAABYktHRACIBR1IAAAACXBIWXMAAAsSAAALEgHS3X78AAAArUlEQVQY01XP11ICQRCF4UaiCBJXQHJeUJKKZHBBQP/3fyBm2AWWc3NqvunpqhHR8Tx48fkDQXESegRv+AkiURueIRZXnUhCSkMa48UZzmTJqcoSvzyXV/IFKVKSW8oEpELVJTXq0miKOy2E9p2YSjp30kXeeHdBT+3x0HfJgKGMPvi8whfjb5EJxsiBqYH+2Yy5fV4sYaV6DZsfyzK3Y9j96pt95MA5vuPfv4YTadsYZ9GpM9EAAAAASUVORK5CYII="
      x="42"
      y="42"
      width="429"
      height="429"
    />
  </svg>
);

export default ReplyIcon;
