export const RetweetIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    preserveAspectRatio="xMidYMid"
    width="19.968"
    height="19.968"
    viewBox="0 0 512 512"
  >
    <image
      xlinkHref="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAAMCAMAAACz+6aNAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAulBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACrJGrzAAAAPXRSTlMAWLOdzMvELUbRP1L0am/8n5K05x69bcVEKLdnaGHNAV/HXmnJbF2/tTYuw2PBH+ivkZX2g/I50FopyqW6W9etvgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAACxIAAAsSAdLdfvwAAACCSURBVAjXXY7XDoJQEAVHRcDexYoFe29gvf//W+4FTcR52D2ZTTYHSCSBlJEWTEsitlIZyOY0+YKIYqlcqdbqhDSaMpxWu4PTjYzZC1ffhUHMDEd8+Zjxj/H+zWQaM7M5i+VqLWmzjcxufziezhf92bc1AVyVuunb/WEI7lPiSzq/ATS2CefzS2jiAAAAAElFTkSuQmCC"
      x="49"
      y="113"
      width="415"
      height="287"
    />
  </svg>
);

export default RetweetIcon;
