export const ShareIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    preserveAspectRatio="xMidYMid"
    width="19.968"
    height="19.968"
    viewBox="0 0 512 512"
  >
    <image
      xlinkHref="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAllBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6C80qAAAAMXRSTlMAvszI3fLhARGbtwXjBAPrJ8feFv4KozfD2CWhC8IrD9XtLGKrwFVmAl1hV0g9n5fbsdP/6QAAAAFiS0dEAIgFHUgAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAB8SURBVBjTxc1JEoJAEETRpEHFCRRFxQlwAsUp7385e1EGYfUBzNWPt6gCvvMMnPlkoM3QN51uT1nYHww5GrcUxZxgmmDGedriYgmsMmC92f5e3WXu9//gPpcoSon0AB6lT2eJC8FKuo4krhZv+nhj8a7xYfHZqL2Igs7eH1NAD7MXj4JZAAAAAElFTkSuQmCC"
      width="512"
      height="512"
    />
  </svg>
);

export default ShareIcon;
